### ISSUE TITLE
Stuck at Waiting for Webtorrent Server

### ISSUE THREAD

**Issue by yaoberh** [noctuid/mpv-webtorrent-hook#7]
Running Manjaro x64. When I try to parse `mpv + magnet link` it just stays at Waiting for Webtorrent Server. Is this a webtorrent problem?

**Comment by noctuid** [comment]
Does it not work with every link or with a specific one? Are you starting mpv like `mpv "magnet:..."`? If it's for a specific link, it could be a problem with the video title or something. If it's for specific links, could you provide one I can test with or let me know if it has special characters?

**Comment by TheHardew** [comment]
I think webtorrent has updated its interface, today after an update it also stopped working for me and it just prints a log file with usage in /tmp and mpv is running forever in the background.

For now `webtorrent [magnet] --mpv` works as a replacement.

**Comment by noctuid** [comment]
Thanks. I think the way this plugin has to work is unfortunate (it broke just because a space in the output was removed). I've created [another plugin](https://github.com/noctuid/mpv-btfs-stream) that uses btfs. It supports torrents with directories of videos or images as well, but btfs is unfortunately slower than webtorrent. It looks like there is another [webtorrent plugin](https://github.com/mrxdst/webtorrent-mpv-hook) that directly uses the webtorrent library instead. @smhmd This might interest you as well.

I will look at this plugin and see if it is missing any functionality. If it can do everything I want, I'm going to mark my plugin as obsolete and recommend it instead.

**Comment by noctuid** [comment]
Okay, I opened a bunch of issues on the other webtorrent plugin. Overall it works well. [Here](https://github.com/noctuid/mpv-webtorrent-hook#comparison-with-webtorrent-mpv-hook) is a list of missing functionalities. @yaoberh I see you made an issue on that plugin previously. Was there some problem with it that led you to try this one?

**Comment by TheHardew** [comment]
I'm not the one you asked the question, but I prefer this plugin, because it's much simpler, just 1 lua file to download. I don't have npm on my system and I'd rather not install it just for one mpv plugin, npm can take a lot of space with it's dependencies and it's one more package manager to update periodically.

If this gets discontinued I'd probably just make a shell script to launch `webtorrent [magnet] --mpv` when it detects a magnet link and `mpv [link]` otherwise. Or maybe I'd try the btfs hook, although I was a little turned off when you said it's slower than webtorrent.

**Comment by smhmd** [comment]
@noctuid I've been using @mrxdst's plugin for a while. The issues I faced were:
-  I couldn't get configuration (through `script-opts/webtorrent.conf` to work -- and so all those features that come with it are therefore blocked)
- Opening a magnet link that has multiple files from history, you have to skip all the played files manually. It does remember the position of the current file once you reach it.
- It does not work with [autosub](https://github.com/davidde/mpv-autosub) (the issue could be with autosub).
![image](https://user-images.githubusercontent.com/46059092/125805966-834592ca-6d6c-456c-a81d-79f1565ad78e.png)
- A minor issue is the red error it displays after `$ mpv <magnet-url>` before starting the hook:
![image](https://user-images.githubusercontent.com/46059092/125804594-45320441-a6e2-4416-922b-082189af9083.png)

**Comment by noctuid** [comment]
@TheHardew For me, I don't care about having to install it through npm. There are so many things my plugin can't do correctly using webtorrent-cli, I'd rather switch. That said, I'm not going to delete this one. I don't think it will be hard to maintain unless webtorrent-cli completely removes the output I'm using.

I can't recommend btfs for now because it's too slow to start by comparison. It seems fine once it's started though. I will try it for a while, mess with my mpv settings, and try other video players to make sure it's not a problem on my end. If it's not my fault, I'll make an issue on the btfs tracker, but I don't know if it's an easily fixable issue. If not for this issue, I would be using btfs because it's dead simple to integrate with and is basically the same as just downloading the torrent first and then calling mpv on it.

@smhmd
Changing webtorrent.conf worked for me.

It looks like btfs-stream will correctly remember the current file for a multi-file torrent.

The last issue is caused because the other plugin uses `on_load_fail` instead of `on_load` like this plugin. Maybe this is also the cause of some of the other issues. Not sure about the autosub issue. It looks like the other plugin is setting the title correctly for the files I've tried.

**Comment by noctuid** [comment]
Well I rewrote this plugin to support torrents with multiple files. Here's a list of improvements and changes:

- Support torrents with multiple files (including image torrents and zipped image torrents)
- Remember and skip to last played file in a torrent
- Allow playing info hashes without webtorrent:// prefix
- Colorize speed output

Breaking changes
- The webtorrent_flags setting is now a json array
- jq and xidel are now required dependencies (since webtorrent cannot give us a json file list)
- The plugin now must be installed as a directory (copy whole directory to mpv scripts directory not just lua file)
- Setting name for enabling/disabling speed output has changed (webtorrent_verbosity -> show_speed)

Hopefully in the future webtorren-cli will include the files in the info command output and I can remove the dependency on jq and xidel.

[Here](https://github.com/noctuid/mpv-webtorrent-hook#comparison-with-webtorrent-mpv-hook) is an updated comparison with the other plugin. I think the only thing it's missing now is the fancy download progress display.

@smhmd I think this plugin should still work with autosub. I'd be curious to know if you find a case where the other plugin doesn't work but this one does.
